modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="tianye"
description='''
Villagers have a Happiness stat (0-10) driven by their home, neighbours, food and light.
Happy villagers offer cheaper and rarer trades; miserable villagers overcharge, and at 0 they quit.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="jade"
    type="optional"
    versionRange="[15,)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
config="${mod_id}.mixins.json"
